services:
  bobashare:
    #image: ghcr.io/bbaovanc/bobashare:latest
    build: .
    restart: always
    environment:
      - APP_BASE_URL=http://localhost:3000/
    volumes:
      - ./storage:/data
    ports:
      - "127.0.0.1:3000:3000"
