[package]
name = "bobashare-web"
version = "0.1.0"
authors = ["BBaoVanC <bbaovanc@bbaovanc.com>"]
edition = "2021"
description = "Simple ephemeral file sharing service"
repository = "https://github.com/BBaoVanC/bobashare"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
axum = { version = "0.6.0-rc.2", features = ["headers", "multipart"] }
bobashare = { version = "0.1.0", path = "../bobashare" }
chrono = { version = "0.4.22", features = ["serde"] }
hyper = "0.14.20"
serde = "1.0.145"
serde_json = "1.0.85"
thiserror = "1.0.35"
tokio = { version = "1.21.1", features = ["full"] }
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
