[package]
name = "bobashare-web"
version = "0.1.0"
authors = ["BBaoVanC <bbaovanc@bbaovanc.com>"]
edition = "2021"
description = "Simple ephemeral file sharing service"
repository = "https://github.com/BBaoVanC/bobashare"
license = "MIT"
default-run = "bobashare-web"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
askama = { git = "https://github.com/BBaoVanC/askama", branch = "axum0.6", features = ["with-axum"] }
askama_axum = { git = "https://github.com/BBaoVanC/askama", branch = "axum0.6" }
axum = { version = "0.6.0-rc.2", features = ["headers", "multipart"] }
axum-extra = "0.4.0-rc.1"
bobashare = { version = "0.1.0", path = "../bobashare" }
chrono = { version = "0.4.22", features = ["serde"] }
chrono-humanize = "0.2.2"
clap = { version = "4.0.12", features = ["derive"] }
config = { version = "0.13.2", default-features = false, features = ["toml"] }
displaydoc = "0.2.3"
duration-str = { version = "0.4.0", default-features = false }
futures-util = "0.3.24"
hex = "0.4.3"
humansize = "2.1.0"
hyper = "0.14.20"
# infer = { version = "0.9.0", default-features = false }
mime = "0.3.16"
mime-db = "1.6.0"
rust-embed = "6.4.2"
serde = "1.0.145"
serde-error = "0.1.2"
serde_json = "1.0.85"
# serde_with = "2.0.1"
syntect = "5.0.0"
thiserror = "1.0.35"
tokio = { version = "1.21.1", features = ["full"] }
tokio-util = { version = "0.7.4", features = ["io"] }
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["trace", "request-id", "fs"] }
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
url = "2.3.1"
# utoipa = { version = "2.2.0", features = ["axum_extras"] }
# utoipa-swagger-ui = { version = "2.0.1", features = ["axum"] }

[dev-dependencies]
pretty_assertions = "1.3.0"
