name: CI checks for every commit

on:
  push:
  pull_request:

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    name: Lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2

      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Test
        run: cargo test

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        run: |
          rustup set auto-self-update disable
          rustup toolchain install nightly --profile minimal
          rustup component add rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo +nightly fmt --all --check

  docker:
    name: Build master Docker image
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          tags: ghcr.io/bbaovanc/bobashare:master
          push: true

  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal
      - name: Build
        run: cargo build --release --locked
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-binaries-${{ matrix.os }}
          path: |
            target/release/bobashare-admin
            target/release/bobashare-web
            # windows is silly
            target/release/bobashare-admin.exe
            target/release/bobashare-web.exe
