name: Deploy rustdoc to GitHub Pages

#permissions:
#  contents: read
#  pages: write
#  id-token: write
#
#concurrency:
#  group: pages
#  cancel-in-progress: false

env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

on:
  push:
    #branches: [ master ]
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install toolchain
        run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal
      - uses: actions/checkout@v4
      - name: Build rustdoc
        run: cargo doc --no-deps
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
