name: Deploy rustdoc to GitHub Pages

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

on:
  push:
    #tags:
    #  - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install toolchain
        run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal
      - uses: actions/checkout@v3
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Build rustdoc
        run: cargo doc --no-deps
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./target/doc

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
